### ISSUE TITLE
FastAPI connection prerequisites 

### ISSUE THREAD

**Issue by tmsincomb** [SciCrunch/quantitative-db#2]
- [ ] package organization (filenames and scheme agreed upon)
- [x] mysql connection config
- [x] outgoing models
- [ ] api endpoint docstrings and function typing for both input and output
